### ISSUE TITLE
No support for OSX HiDPI Retina Display

### ISSUE THREAD

**Issue by GoogleCodeExporter** [garglk/garglk#192]
```
If you run Gargoyle on a HiDPI Retina Display MacBook Pro, the text is not 
rendered sharply.

The new MBP is expensive, so there's a way to test HiDPI modes on a regular 
screen by enabling it via Xcode. 
https://developer.apple.com/library/mac/#documentation/GraphicsAnimation/Concept
ual/HighResolutionOSX/Testing/Testing.html#//apple_ref/doc/uid/TP40012302-CH6-SW
1

I've attached a screenshot.
```

Original issue reported on code.google.com by `dan.fabu...@redfin.com` on 4 Aug 2012 at 5:45

Attachments:
- [Screen Shot 2012-08-03 at 22.44.36 .png](https://storage.googleapis.com/google-code-attachments/garglk/issue-192/comment-0/Screen Shot 2012-08-03 at 22.44.36 .png)

**Comment by erkyrath** [comment]
Following up angstsmurf's comments (http://www.intfiction.org/forum/viewtopic.php?f=38&t=21701&start=10#p120184):

> With the new build script, I managed to compile this with the Retina patch. I noticed no performance problems on my 2014 Macbook, but it took quite a bit of fiddling with the settings to make the text readable. It also seems to report half the actual pixel size of graphics windows.
> EDIT: I suppose it would be more correct to say that *everything* is half size.

My test build produces the same result. Dfabulich notes:

> To make the text readable, I had to double monosize, propsize, leading, and baseline.

But messing around with font preferences this way is silly, and still doesn't cover graphics. (To see that graphics are at half-size, try sensory.blb. You won't see it in Counterfeit Monkey because that game scales the graphical map to the window size.)

I assert that the garglk display engine (draw.c) will need to gain a pixel-size parameter (1 for normal, 2 for double-DPI) which affects all draw operations. This will be more work than the patch we've got, unfortunately.

(Re-attaching patch here, because I don't trust Google Code to stay up in the long term.)

[garglk-retina-r619.patch.txt](https://github.com/garglk/garglk/files/956102/garglk-retina-r619.patch.txt)

**Comment by erkyrath** [comment]
FWIW, I didn't see performance problems in my very brief testing, but I worry that they'll reappear in long play sessions. As I understand it, Garglk keeps increasing the display bitmap size as you play, and x2-DPI mode quadruples the size. (Related: https://github.com/garglk/garglk/issues/195)

**Comment by thirstythursday** [comment]
This patch is kludgy. But thanks for the effort! HiDPI is sweet but many legacy apps look worse than before on such a display.
