### ISSUE TITLE
Full screen mode

### ISSUE THREAD

**Issue by GoogleCodeExporter** [garglk/garglk#197]
```
Can a full screen mode be implemented? Please?

When I play an IF game I like to have only that on my screen. No titlebar. No 
border. The preference for starting full screen or windowed could be in the 
config file. 

A full screen mode creates an other issue. When exiting the game a message 
"press any key to exit" is shownin the titlebar, which isn't shown in full 
screen mode. So the program will wait for a keypress, without notifying the 
user.
This could be solved by:
a. showing the message in the screen itself
b. a pop up message
c. skipping this functionality at all. just quit. my preference. it's just 
annoying.

In case of anything other than option c please consider a steiing in the config 
to make this fuctionality optional.
```

Original issue reported on code.google.com by `marcelsp...@gmail.com` on 16 Dec 2012 at 10:10

**Comment by Emigre** [comment]
+1 to this, I also like the idea of playing in full screen mode

**Comment by cspiegel** [comment]
All platforms but macOS support full screen currently, via the `fullscreen` config option.  I don't know enough about macOS development to add full screen support there, unfortunately.

**Comment by angstsmurf** [comment]
For what it is worth, the standard macOS fullscreen mode (using the green window header button or whatever fullscreen shortcut your OS version and keyboard uses) works fine in Gargoyle and alway has.

**Comment by cspiegel** [comment]
> For what it is worth, the standard macOS fullscreen mode (using the green window header button, the "Enter Full Screen" Window menu item, or whatever fullscreen shortcut your OS version and keyboard uses) works fine in Gargoyle and always has.

Great, thanks for letting me know.  This is, I think, a good enough workaround for the time being, and in fact it's _easier_ to do this than edit the config file.  I'll close this for now, though that doesn't mean that the `fullscreen` option will never come to macOS, just that it's a very low priority.

**Comment by cspiegel** [comment]
Reopening because I realized the original issue also noted a problem with "press any key to exit" while fullscreen, which is definitely the case.

Quick note: that message is potentially useful in general because typing QUIT (or something similar) isn't necessarily the only way for a game to exit. It's entirely possible for a game to quit without warning, and if Gargoyle's window closed then, the text would not be readable.

Gargoyle's current approach is a bit hidden, to be sure. You have to look at the titlebar to see what's going on.  That's not inherently bad but isn't completely obvious.  But for the case at hand, it's absolutely true that it's confusing in full screen.  There's no indication of what's happening, and that's a problem.

One possibility is a dialog box instead of just changing the title.  That would show up for full screen, and in all cases would be a lot more obvious.  A bit more intrusive, though.

**Comment by Emigre** [comment]
Although it's true that you can enter full screen mode in macOS with the green window header button, as mentioned, as a user I personally would prefer a `fullscreen` config option that would automatically enter that mode when the game starts. In any case I completely understand your comment about it being low priority. Thanks for your maintainance work by the way.

**Comment by emigre** [comment]
@cspiegel Oh wow, that's fantastic. Thanks for letting me know and for the implementation!...

**Comment by cspiegel** [comment]
Pull request #810 now fully implements this issue. This does both "a" and "c" from the original issue request, with "c" being optional, and selectable via the config file.

**Comment by cspiegel** [comment]
OK, #810 has been merged in.
