### ISSUE TITLE
Make columns not change with the size of the window.

### ISSUE THREAD

**Issue by eduardomezencio** [garglk/garglk#220]
When you configure the software to display, like, 60 characters per line, you will probably want to keep that even when you resize the window, because it's better to read. I like to maximize the window or put it in full screen (the program does not allow this, but some window managers can do the job by themselves) to get rid of distractions while I play, but then the lines of text get huge and very uncomfortable to read. I think it should just center the content with the number of columns you specified and leave the rest of the space blank, like good ebook readers do.

**Comment by cspiegel** [comment]
@eduardomezencio Well, this is only 8.5 years late, but the `lockrows` and `lockcols` options should do what you're asking:

```
lockcols      1               # set to 1 to enforce col count
lockrows      1               # set to 1 to enforce row count
```

And while we're at it, Gargoyle got support for full screen since you wrote this:

```
fullscreen    1               # set to 1 for fullscreen
```
I'm closing this because, as far as I can tell, what you're asking for is possible, but feel free to reopen and comment if I misunderstood.
