### ISSUE TITLE
jam always rebuilds the entire project

### ISSUE THREAD

**Issue by salty-horse** [garglk/garglk#227]
The `jam` command always rebuilds the entire project, even when I don't make any changes to the files, and simply run `jam` again.

I'm not that familiar with jam, but after some [searching](http://maillist.perforce.com/pipermail/jamming/2004-November/004236.html), it seems the problem is the location of the library files, specifically the `SharedLibraryFromObjects` rule.

**Comment by Tynach** [comment]
@cspiegel has said in a few places that he plans to move the project to CMake eventually. Honestly, I'm surprised that discussion is a bit scattered around in the project, and not directly mentioned in this particular issue.

Given that `jam` is unmaintained (except for the forks), and has so many problems (like this one, which is getting *really* annoying), I'm greatly in favor of moving to CMake. I'd help, except that I'm actually not sure what the best way to go about this is, and don't really know the overall structure of Gargoyle's code (in particular, how the interpreters relate to garglk and what needs to be linked to what).

**Comment by cspiegel** [comment]
At this point, CMake support is complete (I believe) for both Unix and MinGW.  However, I don't have access to a macOS development environment, so that's the main holdup at this point.

I'd really like to switch away from Jam but macOS support is a necessity.  I'll try to see what I can do about Mac support, but I have exactly zero experience developing on Macs.

**Comment by Tynach** [comment]
Sounds fantastic, @cspiegel!

Is it possible to support both cmake and jam at the same time, so that MacOS versions can be built with Jam and others built using CMake?

**Comment by cspiegel** [comment]
Sure, and my CMake branch does that, by virtue of just not deleting any of the Jam build files.  But I really do want to just excise Jam rather than have them co-exist.  I suppose if that's not feasible in the short term I can merge in the CMake branch so that it's at least available to Unix/MinGW users, while macOS continues to be built via the Jamfile.  But that's the road to inconsistency, so it'd be a last resort.

I really do sympathize with the annoyances of the Jam rebuild issue, though, so I can see the utility of having CMake in the next release for that reason alone, even if it's only covering ⅔ of the target systems.

**Comment by cspiegel** [comment]
Jam still rebuilds everything, but now CMake support has been merged in (for all but macOS), so I think this can safely be considered done.
