### ISSUE TITLE
Interface stops responding after clicking hyperlink in Dead Cities glulx story

### ISSUE THREAD

**Issue by BroadcastGames** [garglk/garglk#237]
This story file: http://ifdb.tads.org/viewgame?id=q5el4dphbf7q6e5y

When you click the bottom window HyperLinks, it stops responding.  Ubuntu 16.04 x64 both the gargoyle-free that comes from Ubuntu and my own compiled version off Github source code.

**Comment by salty-horse** [comment]
I'm on Ubuntu 16.10. I see the problem with gargoyle-free, but when I compile the latest version on my own, the hyperlinks don't work at all, so they don't freeze Gargoyle.

Instead, the first time I click the hyperlink, I get the error "Glk library error: put_char: window has pending line request" 18 times, and nothing seems to happen.

**Comment by salty-horse** [comment]
Tried running the game with Windows Glulxe 0.5.3.146 (using Wine). The links don't seem to respond as designed. Sometimes they're clickable, sometimes not. Clicking them will populate text on the command prompt, but do nothing. Pressing enter acts as if I didn't type anything. The game otherwise works fine and doesn't freeze.

**Comment by cspiegel** [comment]
I'm seeing similar behavior in Lectrote.  The following error pops up:

"Quixe run: gli_put_char: window has pending line request"

Then everything freezes up (or, rather, input no longer works).  It looks like a game bug, which may be the result of an Inform bug.

With Gargoyle I'm not seeing "window has pending line request" errors, so that's different than Lectrote.  However, at least from the Gargoyle side, the problem appears to be this:

1. The game requests both line and hyperlink input
2. A hyperlink input comes in
3. The game cancels the line input so it can write to the window (you can't write while input requests are active)
4. The game _does not_ re-request a line event, so no text input is possible; it also fails to re-request a hyperlink event, so no click events come through either

As to 4 above, the game actually does re-request a hyperlink event, _but_ does so on the wrong window, i.e. not the window the click came in on.

So two probable game bugs relating to input.
