### ISSUE TITLE
Lost in the Code - Floyd-like Browser App

### ISSUE THREAD

**Issue by robertmaxton42** [garglk/garglk#268]
So, I'm playing around with an app designed to be a standalone version of what Club Floyd and the ifMUD does - essentially a chatbot that forwards commands to an IF game, but ideally with significantly better rendering capability than a MUD or an IRC can handle. 

It occurred to me that Gargoyle has already done a lot of the work involved in decoding file types and making the rendering look nice, so I thought I'd basically fork off of Gargoyle (and maybe PR the final result if there's interest). But unfortunately I'm thoroughly lost in the code and am not sure where to look - I don't suppose someone could give me some pointers? To be precise, I'm looking for the rendering code, just before the front-end; I'm hoping I can start somewhere around there and then pipe the result to a JS script and a <canvas> tag, or something along those lines. If it comes to it I could also draw to a file and refresh it once a second or so, but that's super kludgey and I'd like something better.

**Comment by curiousdannii** [comment]
For most network integrations it would be better to use [Remglk](https://github.com/erkyrath/remglk) instead.

**Comment by cspiegel** [comment]
Closing because RemGlk is definitely the right approach here.

There are a few things Gargoyle adds on top of Glk, some of which might be useful (colors, unputting strings, explicit reverse video, mainly stuff for the Z-machine), but it would be much easier hacking RemGlk as opposed to splitting out the Glk core from Gargoyle.
