### ISSUE TITLE
Story title at window title bar

### ISSUE THREAD

**Issue by fireton** [garglk/garglk#296]
When I run my z5 file I see `C:\Lots\Of\Different\Folders\mygame.z5 - Bocfel` in window title bar. Is it difficult to implement that the actual name of the story be shown there instead? As far as I understood there is a library callback `garglk_set_story_title` for this. Am I right? Or maybe it's implemented already and I just didn't call proper function in Inform (I'm using RInform - the Inform 6 Russian localization)?

**Comment by cspiegel** [comment]
This feature is already implemented.  The problem is that for a bare .z5 file, there is no information available about the game title.  Instead, you'll want to bundle your game into a Blorb file which supports the [Treaty of Babel](https://babel.ifarchive.org/). My understanding is that Inform 7 can do this automatically, but since you're using Inform 6, you may have to build a .zblorb file yourself.

``garglk_set_story_title()`` cannot be directly called from Inform.  Instead, Gargoyle has to call it based on data it extracts from the game.

Currently, Gargoyle will display the title of any Treaty of Babel-compliant game which includes author and title information, as well as the title of TADS games, because the TADS file format includes that information.
