### ISSUE TITLE
CJK fonts mostly don't work

### ISSUE THREAD

**Issue by alysdexia** [garglk/garglk#299]
Noto Serif CJK SC, Noto Serif CJK TC, Noto Sans CJK SC, Noto Sans CJK TC, Noto Sans Mono CJK SC, Noto Sans Mono CJK TC, MingLiU-ExtB, and Microsoft JhengHei UI fail to the default.  DengXian load the bold and bold oblique sans-serifs but regular and italic fail to the default serif.

**Comment by cspiegel** [comment]
For one of the affected fonts, can you please link to exactly which font files you installed to provide all weights for that font (i.e. Roman/Bold/Italic/Bold Italic, or whatever the appropriate names are for CJK fonts), as well as to a game file that exhibits the problem?

**Comment by alysdexia** [comment]
Pretty well-known: https://www.google.com/get/noto/.  The other fonts belong to Windows.

It looks like the very few games written in CJK use none of the formats garglk supports, but usually Hypercard-like engines like Ren'py (https://www.renpy.org/), Twine (http://twinery.org/), and INterpreter of Simple TExt ADventure (https://instead.syscall.ru/index.html) or HTML engines like Squiffy (http://textadventures.co.uk/squiffy).  Anyhow I still expect a CJK font to display its Latin code for European languages.  Dreamhold (http://ifdb.tads.org/viewgame?id=3myqnrs64nbtwdaz) was the game I tried in.

**Comment by kerrymg** [comment]
I believe I figured out what the problem is. Unfortunately, I don't have a simple solution.

The main issue is that these CJK fonts are TrueType/OpenType font collections (`.ttc` extension with multiple fonts within a single file) and Windows treats them differently in the Registry. Gargoyle uses the fonts' Registry entries to locate the actual font file to pass to Freetype. It does this by locating a Registry key of the form "`$(FONTNAME)  (TrueType)`". This matching works for simple `.ttf` fonts but the `.ttc` fonts use keys named "`$(FONT1) & $(FONT2) & ... (TrueType)`" (each font within the collection file separated by ` & `). Because of the new naming convention the search for the actual font file never succeeds. (This is the case under Windows 10).

Refer to `garglk/winfont.c` source file for full details.

I wonder if we could change the font options in `garglk.ini` to pass the actual font filename. Admittedly an ugly and not very user friendly change.

**Comment by cspiegel** [comment]
Fixed per #303.
