### ISSUE TITLE
Add support for resource streams

### ISSUE THREAD

**Issue by curiousdannii** [garglk/garglk#308]
Shouldn't take too much to bring code across from one of the other Glk libraries.

**Comment by cspiegel** [comment]
I started pulling resource streams from cheapglk, and realized that it'd really be worth it to sync up with all the changes to cheapglk since it was pulled into Gargoyle over 10 years ago.

There's a pull request at #551 which has all the changes.  It's extensive but most of the new code is from cheapglk, so can reasonably be assumed to implement Glk correctly.  This could use a bit of testing, though.  I've run all the Glulx example code through this, which exercises Glk as well as Glulx interpreters,
