### ISSUE TITLE
Won't open Infocom .dat files

### ISSUE THREAD

**Issue by artao5** [garglk/garglk#331]
As per the title. It complains "Not a valid story file."
I DID find a workaround tho, just rename the .dat to .z5 or .z8
Still tho, Gargoyle should just be able to recognize and open an Infocom .dat I figure.
Great software, thanks! :D

**Comment by cspiegel** [comment]
Unfortunately `.dat` is a very generic and common extension.  In fact, Gargoyle already assumes `.dat` is associated with AdvSys games.  As you've discovered, the current workaround is just to rename Infocom `.dat` files to something more appropriate.

At some point I'd like to add detection based on file contents instead of solely relying on the extension, but that's a bit down the road.

**Comment by cibersheep** [comment]
I hope I don't reopen this issue but, it's pretty _simple_ to detect the format with babel. I have use it recently in a qml app and it's working quite well.
Here is the source code: https://babel.ifarchive.org/program.html
`babel -format /url-to-file` will return the format of the gamefile
`babel -ifid /url-to-file` will return its IFID, it can then be used to download xml file info from the internet.
