### ISSUE TITLE
Won't Open Adrift 5 Games

### ISSUE THREAD

**Issue by artao5** [garglk/garglk#333]
Simply put, it won't open them at all. Many Adrift 5 games are now distributed as .blorb files. Still, Gargoyle won't even open .taf Adrift 5 files.

**Comment by curiousdannii** [comment]
Adrift 5 is a completely different format from Adrift 4 and would require a new interpreter. I'm not sure if the Adrift 5 format is remotely compatible with outputing to Glk.

**Comment by artao5** [comment]
Well, I know Fabularium on Android can open them, and the maker of that says it's based on Gargoyle. And it is Glk. So there's that.

**Comment by salty-horse** [comment]
Fabularium is *inspired* by Gargoyle. It's a different codebase.

**Comment by nickbe** [comment]
Interesting. So there IS someone who has already managed to write a new interpreter for Adrift5.

**Comment by curiousdannii** [comment]
Or they've bundled Adrift with Mono. Fabularium has a common launcher but doesn't have to use the same interpreter framework for different formats.

It would be nice to know what exactly Fabularium is doing. Unfortunately it doesn't appear to be open source.

**Comment by salty-horse** [comment]
I have contacted the author last week, saying they can't just claim it's open-source without providing a link to the source. I got no response yet.

**Comment by kerrymg** [comment]
I believe this is the source code for ADRIFT 5, right here on GitHub:

https://github.com/jcwild/ADRIFT-5

Still unsure how _Fabularium_ runs these stories. There is no Mono run-time in the GooglePlay APK. It's possible the author used the above sources to update the existing Scare interpreter.

OTOH, the ADRIFT 5 sources include a project for a WebRunner (in addition to the MonoRunner), so maybe the generated ASP.NET (?) web-site/pages is bundled within the app.

**Comment by artao5** [comment]
For what it's worth, I've found the author of Fabularium to be quite responsive to emails.

**Comment by cspiegel** [comment]
Fabularium comes with a new Adrift interpreter called Bebek, which appears to be written in Java, and guided by the Adrift 5 source code posted above.  As far as I know the Bebek souce isn't available, and in any case wouldn't be usable with Gargoyle as-is, because Gargoyle has no support for Java.

I'm not really familiar with C# or Java, but I suspect there's some way to bind to libgarglk from them; however, integration of C# or Java interpreters with Gargoyle faces some hurdles because there would have to be extra work done to ensure a valid interpreter is available and can be launched.

However, given that the source is available, a port to C or C++ is at least feasible if anybody wants to go to the effort to do it.

**Comment by nickbe** [comment]
Who made the Adrift 4 interpreter for gargoyle back then?

**Comment by cspiegel** [comment]
The Adrift 4 interpreter (Scare) was written years ago by Simon Baldwin, amusingly as a port of a Java interpreter written by Mark J. Tilford, although it wasn't written for Gargoyle directly, but includes Glk support so it can work with Gargoyle.

The Bebek Java source appears to be available [here](https://github.com/tccowper/fabularium/tree/master/app/src/main/java/com/luxlunae/bebek).

**Comment by nickbe** [comment]
Would it be possible to integrate the bebek interpreter in gargoyle then? Aside from the obvious Java dependency this would be a big thing. 
Or do you thing is it possible to port it to C++ without too much trouble?

**Comment by cspiegel** [comment]
As far as I know, Fabularium is a Glk implementation, so Bebek presumably uses Glk.  I don't know Java, but I'd imagine there's some way to call into C libraries from Java.  If so, it may be as “easy” as linking in libgarglk.so and routing all Glk calls through it.  Theoretically it shouldn't be much work, but take that with a grain of salt, because I really have no familiarity with Java.

As for porting to C++, it'd be a large undertaking.  Java and C++ are broadly similar languages, but it'd still be a lot of work.  It'd be fantastic if somebody were to undertake that, but it'd also be pretty surprising.

**Comment by cspiegel** [comment]
With the merging of the FrankenDrift interpreter, we now have Adrift 5 support.
