### ISSUE TITLE
Unicode input not supported on Windows

### ISSUE THREAD

**Issue by KarolS** [garglk/garglk#341]
System: Windows 10 Home
System locale: Polish
Versions tested: both `stable-2011.1` and the experimental build from https://github.com/garglk/garglk/issues/285#issuecomment-341520320; both behave the same

The problem does not occur on Linux, only Windows.

I'm unable to type any character outside the Windows-1250 charset, regardless of the keyboard layout.
This makes playing IF in Russian impossible.

![obraz](https://user-images.githubusercontent.com/1790750/48973634-bc741780-f043-11e8-9478-73a58b7f1d45.png)
In the first input, I switched to a Russian keyboard layout and typed `инфо`, just like the game suggested. As you can see, the word was not recognised.
In the second input, I switched to a custom keyboard layout and typed `£ å ï ‟ ”`. The game recognised the first symbol as "L", which in this game is a shortened version of "look" for some reason.
The same problem occurs regardless of the interpreter.

Pasting text from clipboard works fine: 
![obraz](https://user-images.githubusercontent.com/1790750/48973578-75d1ed80-f042-11e8-8135-fd0361fea1d8.png)

I think the problem might be caused by reading input via `WM_CHAR` events instead of `WM_UNICHAR`: https://github.com/garglk/garglk/blob/master/garglk/syswin.c#L845

**Comment by DavidKinder** [comment]
It isn't necessary to handle WM_UNICHAR to process input in different languages. However, the WM_CHAR handling code isn't quite right: it converts the character to Unicode using codepage CP_ACP, which just means "whatever the system code page is". That's fine in most cases, but here the OP noted that they "switched to a Russian keyboard layout", which will change the codepage that the WM_CHAR messages are in.

The fix is (probably) to handle the Windows WM_INPUTLANGCHANGE message, and store the new code page message from that message, then use that code page identifier when handling WM_CHAR.

**Comment by KarolS** [comment]
If I'm reading the documentation correctly, WM_INPUTLANGCHANGE only fires when changing the layout, so if I change the layout first and launch the interpreter later, it will not pick up the layout.

I also checked how Gargoyle behaves if I change the keyboard layout before launching it, the layout is ignored.

**Comment by DavidKinder** [comment]
It's been a while since I had to deal with code around this sort of issue, but from what I remember, the important thing is that the input language (and therefore code page) is a per-top-level-window setting, not a system setting. So when a window is first created it always has the system default input langauge, which can then be changed with the language bar.

You can see this by changing the input language in the language bar for one window, then switching the focus to another window - you should see the input language in the bar go back to the default, because the act of changing the value only affects the active window.

**Comment by KarolS** [comment]
I tested Gargoyle with Locale Emulator and it turns out that Gargoyle doesn't use the codepage of the current keyboard layout, but the codepage of the current locale.
In all cases below, I selected the keyboard layout _before_ launching Gargoyle:
Polish locale + Polish layout = OK
Russian locale + Russian layout = OK
Polish locale + Russian layout = fail, as shown in the original submission
Russian locale + Polish layout = fail, Polish accented letters don't show up at all – not even as random Cyrillic or question marks

I looked around how other programs handle this thing and I found this in the Tk library: http://core.tcl.tk/tk/artifact/f7dd05d37f9668b4


    // this is from initialization:
    if (GetLocaleInfo(LANGIDFROMLCID(PTR2INT(GetKeyboardLayout(0))),
	       LOCALE_IDEFAULTANSICODEPAGE | LOCALE_RETURN_NUMBER,
	       (LPTSTR) &lpCP, sizeof(lpCP)/sizeof(TCHAR))
	    && TranslateCharsetInfo(INT2PTR(lpCP), &lpCs, TCI_SRCCODEPAGE)) {
	UpdateInputLanguage((int) lpCs.ciCharset);
    }
    ...
    case WM_INPUTLANGCHANGE:
        UpdateInputLanguage((int) wParam);
    ...
    len = MultiByteToWideChar(keyInputCharset, MB_ERR_INVALID_CHARS, tsdPtr->event.xkey.trans_chars,
            tsdPtr->event.xkey.nbytes, buf, 4);

(`UpdateInputLanguage` does few things, but what matters here is that it stores its argument unmodified in a global variable `keyInputCharset`)

I think a similar approach could work in Gargoyle.

**Comment by KarolS** [comment]
I checked the 2019.1 release and the issue is still present.

**Comment by KarolS** [comment]
Works just fine on this build: https://github.com/garglk/garglk/actions/runs/1440005049

![obraz](https://user-images.githubusercontent.com/1790750/141216204-eebdc216-5f16-4af7-8122-32cb368b25f8.png)

I guess it can be closed.

**Comment by cspiegel** [comment]
Thanks for following up on this one.  Glad we've got Unicode moving in the right direction.
