### ISSUE TITLE
Program Will Not Run on 10.15

### ISSUE THREAD

**Issue by honeydrops-the-sensual** [garglk/garglk#349]
Since it's a 32-bit client, it won't run on 10.15! Any chance of an update?

**Comment by cibersheep** [comment]
You can update to 19.04 which is stable realease

**Comment by tomku** [comment]
OP is referring to the recently-released MacOS 10.15, not an ancient (and impossible) version of Ubuntu. MacOS 10.15 removed support for 32-bit binaries and the version of Gargoyle available on the Releases page is a 32-bit binary.

The source has supported building 64-bit binaries for many years, but there hasn't been a release on this repository since that support was added. I'm using binaries from [Andrew Plotkin's fork](https://github.com/erkyrath/garglk/releases), which I can verify are entirely 64-bit since at least the November 2016 release.

**Comment by cspiegel** [comment]
The newest release should now support macOS 10.15.
