### ISSUE TITLE
Bocfel: Initial slash in input breaks Beyond Zork definitions menu

### ISSUE THREAD

**Issue by angstsmurf** [garglk/garglk#399]
Here is another way to break the Beyond Zork definitions menu: move to the beginning of a line, by deleting the preloaded input text or moving past it with the left arrow key, type a slash and enter. Bocfel will print a long help message about meta commands in the buffer window, and the input field will move to the left edge of the line below its proper position.

**Comment by cspiegel** [comment]
This kind of thing also happens in the game _My Angel_ when in novel mode.  I fixed this locally a couple months ago after testing with _My Angel_, but it turns out to only have been a partial fix in light of this bug report: BZ works _better_ in my local branch, but due to the fact that it's using preloaded input, it's not perfect.  The preloaded text makes it a bit tricky, but I'm working on a fix.  Thanks for the report!

**Comment by cspiegel** [comment]
@angstsmurf OK, a new Bocfel release has been merged in which fixes this issue.  And should also fix #384, #385, and #395.

If you'd like to double-check that all work for you, please do so, then the issues can be closed.  Otherwise I'll just close them, as my testing indicates they're now working.

**Comment by angstsmurf** [comment]
Yay, it works. Excellent job!

**Comment by angstsmurf** [comment]
Right, there is still a very small glitch: if you move the cursor all the way to the left, type a slash and hit enter, the command will be echoed with an extra vertical bar at the end, which is a bit fiddly to get rid of. But that is a nitpick.

**Comment by cspiegel** [comment]
Interesting; it looks to be because there's nothing erasing the text that was previously there.  It can be more "obviously" recreated by typing in a very long, nonsense meta-command, like "/aaaaaaaaaaaaaaaaaaaaaa".

The fix is to overwrite the user's input with spaces.  It can't be completely guaranteed to be right in all cases, but it's at least better than leaving the text there.  And it seems to be fine for Beyond Zork.

Here's a patch that seems to work: [bz.txt](https://github.com/garglk/garglk/files/5820953/bz.txt)

**Comment by angstsmurf** [comment]
That works great! Thanks for all your hard work.

**Comment by cspiegel** [comment]
I appreciate the beating you're putting Bocfel through. All these weird edge cases would have gone undiscovered if not for your poking and prodding.

And there are still a couple more little issues related here: Bocfel tries to print a prompt after a meta command (because it can't ask the game to do so, since prompt printing has long passed).  But when the cursor is in the upper window, prompt printing should be disabled (try `/ps` then `/pop` in *My Angel*, for example).

And, if you do `/ps` and `/pop` in *My Angel*, you'll *also* see that the text is not blanked.  My earlier patch didn't consider the path where a game was restored.

Yet another patch: [bz.txt](https://github.com/garglk/garglk/files/5823442/bz.txt)

**Comment by angstsmurf** [comment]
Yes, I see the problem. And the patch fixes it. Thanks again!
