### ISSUE TITLE
garogle can not open libgarglk.so

### ISSUE THREAD

**Issue by silverhikari** [garglk/garglk#412]
i am using Ubuntu 20.10, with freetype jam, and when i build and install gargoyle i get this message even though libgarglk.so is both executable and in the same directory "./gargoyle: error while loading shared libraries: libgarglk.so: cannot open shared object file: No such file or directory", and when i try to run the lib by it self(just to see if anything happens) i get a segmentation fault.

both error and buildlog using stdout: https://paste.ee/p/QQxSI

**Comment by cspiegel** [comment]
Shared libraries are not loaded from the same directory as binaries (unlike on Windows); instead, a prearranged set of directories is used (from `/etc/ld.so.conf` plus some fixed ones).  Either move `libgarglk.so` to one of these directories, or add a new path for the dynamic linker using the `LD_LIBRARY_PATH` environment variable, for example:

```
LD_LIBRARY_PATH=$PWD ./gargoyle
```
But then the `gargoyle` executable is just a loader for the actual interpreters, which won't be found by it.  `jam install` will install things system-wide in a way that Gargoyle will be able to find.  Otherwise you'll have to run the binaries directly, e.g.

```
./build/linux.release/bocfel/bocfel zork1.z3
```
But again, `LD_LIBRARY_PATH` will have to be set properly if you don't install it system-wide.
