### ISSUE TITLE
Unix - allow running gargoyle from the build dir without installing

### ISSUE THREAD

**Issue by salty-horse** [garglk/garglk#455]
To run gargoyle from the build directory (without running `make install`), I found that I have to edit `GARGLK_INTERPRETER_DIR` in `garglk/CMakeLists.txt`.

It is reasonable to change gargoyle to consult a `GARGLK_INTERPRETER_DIR` environment variable before using the hard-coded value?
Or, even to look in `terps/` in the current directory as a first attempt.

**Comment by cspiegel** [comment]
A very reasonable request.  I've got a merge request at #458 to implement this (specifically, to look up the directory from the environment variable `GARGLK_INTERPRETER_DIR`).  Please give it a test to see if it suits your needs.

Note that this *replaces* the normal lookup, so if the variable is set but no interpreters are there, Gargoyle will not fall back to the system directory.  This is largely because the code to find and load interpreters isn't particularly suited to such a modification, at least until it's been cleaned up some.

**Comment by salty-horse** [comment]
Thanks, it works! The new detailed error message when the interpreter can't be found is also useful.

I would suggest adding it to the `INSTALL` documentation

**Comment by salty-horse** [comment]
Looks good

**Comment by cspiegel** [comment]
Merged.
