### ISSUE TITLE
Simultaneous Blorb games broken on macOS

### ISSUE THREAD

**Issue by angstsmurf** [garglk/garglk#464]
I haven't tested this thoroughly, but it seems like eeaff50 broke the ability to play multiple Glulx games simultaneously, or several Glulx games in a row without restarting Gargoyle. Trying to open a second Glulx game will no longer show any window at all.

This feature seems to be working fine with the other Gargoyle interpreters I've tried so far (Level 9 and Bocfel). Switching Glulx interpreter to Git does not seem to help.

macOS Big Sur 11.4, MacBook Pro 2016.

EDIT: After further testing, it seems that is is playing from Blorb files that is broken. .ulx files work fine, while .zblorb files do not. Updated the title accordingly.

**Comment by cspiegel** [comment]
Well that's an unfortunate bug!

I can't test because I don't have a Mac, but I do think I found the problem.  It looks to be a result of using global variables.  I've got a fix about ready to be pushed and tested.

Maybe it's time to sweep through the code and eliminate as many globals as possible...

**Comment by cspiegel** [comment]
@angstsmurf OK, I've got it in my repository in a branch called `blorb-launch` (https://github.com/cspiegel/garglk/tree/blorb-launch) if you're willing to give it a spin.

**Comment by angstsmurf** [comment]
Yes, that branch seems to fix it!

**Comment by cspiegel** [comment]
OK, merged #465, so it should be working in master now.
