### ISSUE TITLE
The Lurking Horror: sound doesn't loop

### ISSUE THREAD

**Issue by mogarithm** [garglk/garglk#502]
I tested the first sound effect in Infocom's The Lurking Horror (steps given below). On Windows Frotz, the sound of tribal drums plays continuously in a loop. On Gargoyle (via Bocfel), it plays just once and stops. I think the Windows Frotz behaviour is the correct one. Is there a "loop" flag that Gargoyle/Bocfel is not handling?

Steps:
READ ASSIGNMENT. TURN ON COMPUTER. LOOK AT COMPUTER. LOGIN 872325412. PASSWORD UHLERSOTH. EDIT PAPER. CLICK ON PAPER. READ PAGE. AGAIN. AGAIN. AGAIN.

Z-code file used: https://eblong.com/infocom/gamefiles/lurkinghorror-r221-s870918.z3
Blorb file used: https://www.ifarchive.org/if-archive/infocom/media/blorb/Lurking.blb (file was then renamed to match z-code filename)

**Comment by cspiegel** [comment]
You are correct, repeating is the proper behavior.  This is fixed in the latest Bocfel (which has been imported into Gargoyle), and the fix will be in the next release.

If you're comfortable building from source you can download and build master, to verify that it's working for you.  I'll leave the issue open for the time being, and you can close (or not) if you're satisfied that it's fixed.
