### ISSUE TITLE
Building (and running) on Intel Mac using cmake?

### ISSUE THREAD

**Issue by angstsmurf** [garglk/garglk#534]
The `gargoyle_osx.sh` creates a working app just fine, but I can't make a working Gargoyle install on macOS using cmake. Is that even supported?

Following the instructions in INSTALL.md on Big Sur, it seems to build fine, but will install by default in `~/garglk/build/dist/` rather than `/usr/local`. The suggested `cmake .. -DCMAKE_INSTALL_PREFIX=/usr` has no effect.

Never mind, I try running  ~/garglk/build/dist/gargoyle:

```
dyld: Library not loaded: @rpath/libgarglk.dylib
  Referenced from: /Users/administrator/garglk/build/dist/gargoyle
  Reason: image not found
zsh: abort      ~/garglk/build/dist/gargoyle
```

So I try the suggested
```
$ cd build
$ export GARGLK_INTERPRETER_DIR=$PWD/terps
$ ./garglk/gargoyle
```

And the result is… nothing? A process named gargoyle seems to be running at 0% cpu but not showing anything.

I am obviously not very good with the command line or with cmake, so any help is appreciated.

**Comment by cspiegel** [comment]
> The `gargoyle_osx.sh` creates a working app just fine, but I can't make a working Gargoyle install on macOS using cmake. Is that even supported?

It wasn't, because macOS was "special" (same as Windows) in that the only expected target is a bundle.  The generic build instructions are more geared toward non-Apple Unixes; not by design, but because I didn't even think about it!

I've got a pull request at #536 that addresses this, to some degree. By default now, a standard install is done on macOS, so you can install it to `/usr/local` (or anywhere else) as you would on Linux, FreeBSD, etc.  To get the original behavior, pass `-DDIST_INSTALL=ON` to CMake.  This is automatically done by `gargoyle_osx.sh`.

Here's the big caveat: this does _not_ work with the Cocoa interface.  That interface is written in such a way that it expects everything to be in a bundle.  It _does_ with with the Qt interface, and I'd recommend Qt6, because Qt5 takes some finessing to get CMake to find it. So:

```
cmake -DINTERFACE=QT -DWITH_QT6=ON
```

The Qt interface differs from Cocoa in that it doesn't provide any menus for opening files.  But in my quick testing, it all does work, so at least you can get something going.

I suspect it'd be possible to modify the Cocoa interface to support both installation types, but that'd be something for the future.

**Comment by angstsmurf** [comment]
Thanks for this! It works now.

This is really a separate issue, but it seems to still link SDL and SDL_mixer even if I set -DSOUND=none or  -DSOUND=QT.

**Comment by angstsmurf** [comment]
This works fine now, so I'll close it. I did kind of hope that it would help me get closer to fixing #522, but no such luck. That is a different issue, however.
