### ISSUE TITLE
Geas bugs in Gathered in Darkness

### ISSUE THREAD

**Issue by angstsmurf** [garglk/garglk#572]
When adding Geas support to Spatterlight, I encountered issues in several of the games I tried (which admittedly was only four or five), and the same problems seem to manifest in Gargoyle as well. This is just an easily reproduced example:

At the third turn of [Gathered in Darkness](https://ifdb.org/viewgame?id=j737kw3x3j1h8c7e), you awake in your room. The original [Windows Quest 4 runner](https://www.ifarchive.org/if-archive/programming/quest) displays the text "You see a piece of paper on the desk that you are certain was not there last night." This text is absent in Gargoyle. Typing READ NOTE in official Quest will print the contents of the note and add it to your journal, but Gargoyle will reply "I don't understand your command. Type HELP for a list of valid commands."

Going west will take you to your bathroom, where "a single large, unlocked cabinet door is below the countertop." Typing OPEN CABINET in official Quest will open it and show a flex coupling inside. The same command in Gargoyle will again give the same "I don't understand your command."

These bugs do not seem to be a recent regression. They exist in release 2011.1 as well.

**Comment by cspiegel** [comment]
I just built geas 0.4 from https://www.ifarchive.org/indexes/if-archiveXprogrammingXquest.html, and it exhibits the same behavior.  I guess Quest games have always been buggy with geas.  Not that it's necessarily a surprise: I don't think there's a specification geas was written to.  There are comments in the source indicating uncertainty in parts of the implementation, including 38 "TODO" notes.

Geas also doesn't support modern Quest games (see #286).  I wonder if it's worth keeping Quest support when it's potentially buggy in a somewhat silent way, i.e. not crashing, but subtly failing to do things which it ought to do.  At any rate I don't have the knowledge to fix geas.

**Comment by cspiegel** [comment]
As far as I can tell, there are 4 IFComp old-style Quest games:

* [Lovesong](https://ifdb.org/viewgame?history&id=7333jblqiou6je15)
  * Doesn't work in Geas (no text, just a prompt, and typing anything results in the interpreter exiting)
* [Blade Sentinel](https://ifdb.org/viewgame?id=45wncrvi1rq0na9q)
  * Starts up. It seems broken ("look" results in nothing being printed).  A review on IFDB by MathBrush says "gargoyle was having some problems" running it.
* [Beam](https://ifdb.org/viewgame?id=inj3mzj11zjf31mq)
  * Seems to work by following a walkthrough. Some text looks like there are object naming errors ("You are Up in a Tree. ... You can go out to Tree2.")... but that could just be a bad game implementation, not an interpreter problem.
* [Gathered in Darkness](https://ifdb.org/viewgame?id=j737kw3x3j1h8c7e)
  * Buggy as described here

75% of the games are noticeably broken.  There are a few other old-style Quest games on IFDB, but they're few and far between.  Modern Quest games don't even run.  I think it's worse having almost completely useless Quest support than not having Quest support at all.  Unless a strong case can be made otherwise, I'm just going to remove Quest support from Gargoyle.  It's broken, and, to be blunt, there don't appear to be any old-style Quest games that would make it worth trying to fix.

**Comment by cspiegel** [comment]
"Fixed" by #577.

If the modern Quest interpreter is ever rewritten in a portable language, I'd love to re-add support.
