### ISSUE TITLE
Support for 3x graphics scaling

### ISSUE THREAD

**Issue by johnnovak** [garglk/garglk#600]
Currently, images in Magnetic Scrolls adventures are displayed with 2x integer-scaling, as shown in the first image. This is a bit small on larger screens; it would be nice to add support for optional 3x scaling in the config. I've created a mockup for this on the second image.

Perhaps it would make sense to make this a global option, as pretty much all old text adventures feature only low-res graphics (usually only 320 pixels wide).

I assume this is an easy enough feature and I would do it myself, it's just usually a bit overwhelming to get stuff build on Windows...

![fish2x](https://user-images.githubusercontent.com/698770/145663515-98903e1c-ee7b-4eef-8227-48de80bd0e58.png)

![fish3x](https://user-images.githubusercontent.com/698770/145663517-aeaccd7d-a528-43ca-82c2-e14a300b4ab3.png)

**Comment by johnnovak** [comment]
Actually, probably the most flexible solution would be to allow setting the integer scaling factor to an arbitrary number between say 1 and 8 like in the Magnetic interpreter:

![image](https://user-images.githubusercontent.com/698770/145664342-69b56a78-ecf9-49eb-9cdd-4c2697fecbcd.png)

**Comment by cspiegel** [comment]
#805 implements this, although in a somewhat no-frills manner. The main sticking point is that in Gargoyle, interpreters are separate from the Gargoyle core. The Gargoyle config file affects the interface, but not the way the interpreters work. However, you can use the config file to pass arguments to interpreters, and for now, that's how this is implemented. You have to add something like this to get 3x scaling:

```
[ *.mag ]
terp magnetic -sc 3
```
This is not ideal: first, the `terp` command is too low level, requiring you to know that the interpreter for Magnetic Scrolls games is called `magnetic` and then knowing that the newly-added `-sc` argument is for scaling images. Next, this only works for games with the `.mag` extension, but Gargoyle can probe file types, so you could launch Magnetic Scrolls games with any extension, since Gargoyle will detect them. As it stands, there's no way to tell the config file "apply this to Magnetic Scrolls games" instead of "apply this to games ending in `.mag`".

But the first hurdle's the hardest, and now there's at least a way to set the scale factor.  I'll try to find a cleaner way to do it, though.

**Comment by johnnovak** [comment]
Thanks for getting back to me and adding support for this @cspiegel. From a practical point of view, I think the feature is perfectly fine, but sure if there's a nicer or more flexible way, that's even better 😄

**Comment by cspiegel** [comment]
Merged.
