### ISSUE TITLE
Missing fonts for MacOS arm64 release

### ISSUE THREAD

**Issue by binary-sequence** [garglk/garglk#644]
# Versions

- Gargoyle version: gargoyle-2022.1-mac-arm64.dmg
- MacOS version: Monterrey 12.3.1 (21E258) arm64 (M1)

# How to reproduce

1. Open gargoyle
2. Try to open a .blb file
3. See error

```
Fatal error

Unable to find font Gargoyle Mono for Mono Regular, and fallback Gargoyle-Mono.ttf not found
```

# Extra info

In this intfiction comment https://intfiction.org/t/gargoyle-2022-1/54367/22
it is said that it may be related to a previous garglk.ini file, but this is the first time I install/use gargoyle.

**Comment by cspiegel** [comment]
This _shouldn't_ be related to the issue linked on intfiction: your error message indicates that the proper fonts are being searched for, but just not found.  The fonts _are_ in the `gargoyle-2022.1-mac-arm64.dmg` file, so offhand I'm not sure why it can't find them.  I don't have an ARM macOS, so I can't directly test to see what's happening.

macOS is supposed to make fonts in the bundle available to the program, as though it were a system font.  But if that's not happening, you may be able to work around this by installing the Gargoyle fonts system wide.  I'm attaching [an archive of the Gargoyle fonts](https://github.com/garglk/garglk/files/8547595/gargoyle-fonts.zip).  Install these, and they should be available to Gargoyle.

Another option is to try the Intel version.  At the very least it'd be interesting to know whether you have the same problem with both, or if there's something odd with the ARM version on your system.

**Comment by binary-sequence** [comment]
Thanks for the quick answer.

I have tried both, the intel version and installing the fonts manually. I get the same error.

Also, I have discovered something more, the error happens with .blb files but, it doesn't happen with .gblorb files.

Not sure if it helps, but here is one I have tried and doesn't work: http://www.caad.es/jarel/games/Venenarius_Verborum.zip

**Comment by cspiegel** [comment]
Do you have an older Gargoyle version lying around anywhere?  Font loading has nothing to do with the file type so there should be no difference between the two.

My initial guess would be that an older version of Gargoyle is registered to open blb files; can you check if that's the case?

**Comment by binary-sequence** [comment]
No, this is the first time I have installed/used gargoyle. I just discovered today it existed.
Also, I am not opening the files with double click, I am executing gargoyle from Applications, then file->open and selecting the file.

**Comment by angstsmurf** [comment]
I think this happens because the *Venenarius Verborum* folder contains a custom `garglk.ini` file with custom font settings which Gargoyle will detect and use for this particular game. I've seen similar errors with other games that have a custom 'garglk.ini`.

Not sure why Gargoyle won't find the fonts, though.

**Comment by cspiegel** [comment]
Great insight @angstsmurf.  That's certainly it.  That `garglk.ini` uses `propr`, `propb`, etc, to specify built-in fonts, as was used in prior Gargoyle releases, but due to licensing issues, built-in fonts aren't supported.  Normally that wouldn't be a problem, but due to a bug on Mac in the 2022.1 release, fallback fonts aren't working.  The quick fix is to simply remove lines 52-60 in the Game's `garglk.ini` file (those specifying fonts), and the defaults will be used.

The next release will include a fix for the fallback fonts.

**Comment by binary-sequence** [comment]
Thanks, removing lines 52-60 works. :)

**Comment by cspiegel** [comment]
Good to hear!  I'm closing this issue because there's already a fix in, and it'll be available next release.
