### ISSUE TITLE
Any way to keep the window size after closing the Software?

### ISSUE THREAD

**Issue by Schnubbirunkel** [garglk/garglk#647]
I know you could change the zoom lvl in the config file, but that doesn't really work that well. Is there a way for gargoyle, to remember the window size from last time the software was running? That would be awesome and would make Gargoyle pretty much the perfect Interpreter for me.

**Comment by cspiegel** [comment]
If your goal is to have a specific size (i.e. you don't like the default, and want a fixed size that you prefer), you can do that with the `rows` and `cols` settings in the config file.

But even if that were good enough for your purposes, it's a reasonable request to have Gargoyle remember window size.  It can't be the default, since that'd be a big change, which also means there'd have to be a new config option flag indicating whether to store the window size.  The config file just keeps growing...

Doing this for Unix/Windows should be very simple, as it'll just be a few new calls into Qt.  For Mac, I'll have to look into it a bit more.  But I see no reason this can't/shouldn't be added for the next release.

**Comment by Schnubbirunkel** [comment]
Hey, thank you for answering!
Yeah, I did figure that out with the rows and cols. It looks pretty nice now, but I still have to move the window from the left edge of the screen to the middle every time. Really not a big deal, but IF that is an easy fix, that would be amazing.
I don't think it's related, but a similar problem exists with the file browser not remembering, where you were last time. 
So every time you start the program, you need to search for your games folder again, instead of it remembering, where that folder was. 
And the same thing with loading or saving games. I save my games on my NAS, so I can switch between devices to play. So every time, I want to save my progress, I need to go through all my folders to get to the right one.
I really wish I could help with that. I feel awful just pointing out flaws, instead of helping to fix them, so if there is anything, a novice could help with, please let me know.

**Comment by cspiegel** [comment]
> Yeah, I did figure that out with the rows and cols. It looks pretty nice now, but I still have to move the window from the left edge of the screen to the middle every time. Really not a big deal, but IF that is an easy fix, that would be amazing.

I'll still have to work out details, but I've got some proof of concept code for saving/restoring window size and location on Unix/Windows, and window size on Mac, with location maybe to follow (I'm very unfamiliar with Mac development, so it's more of a slog to get that stuff done; I'm not the original author here so some stuff I'm just blindly wading through).

> I don't think it's related, but a similar problem exists with the file browser not remembering, where you were last time.
So every time you start the program, you need to search for your games folder again, instead of it remembering, where that folder was.
And the same thing with loading or saving games. I save my games on my NAS, so I can switch between devices to play. So every time, I want to save my progress, I need to go through all my folders to get to the right one.

So the macOS code apparently already does this (though probably as a function of the OS).  For Unix/Windows, it ought to be possible, as Qt allows you to supply a default directory, and that _should_ be something that can be saved and reused, at least once a file is selected (i.e. if you just navigate to a new directory but don't select a file, and close the dialog, I don't think that can be saved, as the information is discarded).

Anyway, for the main program loading, this would be a nice-to-have feature for sure.  I'm not entirely certain about saving/loading.  _Something_ would probably be better than what exists now; maybe the last save directory, but maybe not. For example, the directory containing the game file might make sense as opposed to the last-used directory.  I mean, both ways "make sense" insofar as they're perfectly valid, but they're just incompatible use cases.  Somebody may prefer dropping saves next to their games, in which case storing the last directory isn't good, but as evidenced by your request, that's not always desired...

This is something I'll have to think about. My immediate reaction is to just make it a config option but I think I'm in a very small minority who loves having each and every thing configurable.

> I really wish I could help with that. I feel awful just pointing out flaws, instead of helping to fix them, so if there is anything, a novice could help with, please let me know.

Not a problem at all!  Reporting bugs/requesting features is helpful.  Feel free to create any issues you think are necessary.  If you ever want to roll up your sleeves and get a bit dirty, as a non-coder, documentation is _always_ lacking.  There's a much-neglected Wiki that you're free to add to.  Even just a few edits here and there would be beneficial for other users.  Do as much or as little as you'd like.

**Comment by cspiegel** [comment]
I've implemented this in a local branch that can be tested.  Window size works on all platforms (assuming the operating system isn't configured to override user preferences). Window location doesn't work on Mac, but does work on all other operating systems. The following are available for easy testing without needing to install:

[Linux (x86_64 AppImage)](https://nightly.link/cspiegel/garglk/actions/runs/2620017325)
[Windows (all)](https://nightly.link/cspiegel/garglk/actions/runs/2620017321)
[macOS (unsigned disk image)](https://nightly.link/cspiegel/garglk/actions/runs/2620017328)

To use this, you need to add the following to your config file:

```
save_window size location
```
You can specify either `size`, `location`, or both, depending on what you want to save.  If you've got any feedback on ways to improve the config, let me know.

At the moment, if you disable saving, any existing preferences are _not_ deleted. Which is to say, if you save the size, disable saving, then later re-enable saving, the old saved size will be restored.  My feeling is that things ought to be deleted if disabled; any input on that?

**Comment by Schnubbirunkel** [comment]
Ok, I've tried the Windows version, and it works almost perfectly.
One small issue seems to be, that the window wants to center itself every time, you restart gargoyle:

Before the Restart
![Before Restart](https://user-images.githubusercontent.com/35907349/177503694-8e7e0aec-eb9b-4438-9eaa-81b1b3e0b8df.jpg)

After the Restart
![After Restart](https://user-images.githubusercontent.com/35907349/177503805-8063a051-3a46-4e63-bcac-7b09739ff9b7.jpg)

It's only a very small amount, but It's enough to notice. I would be perfectly fine with it, a lot of programs seem to do that anyway. 

For your settings getting deleted, when you disable the saving:
I really like it. I know it could be trouble, if someone screwed up their window size completely and can't reset it anymore, but it's really convenient like this. Up to you, I guess, I would keep it this way.

**Comment by cspiegel** [comment]
> It's only a very small amount, but It's enough to notice. The weird thing is, that every time you restart gargoyle, the window slips down a bit more. That sounds like a strange Windows bug. I remember seeing that exact issue with other programs on Windows too.

Interesting; it happens on Linux (Plasma), too.  I'm not sure if there'll be an easy fix, but I'll see about it.

> For your settings getting deleted, when you disable the saving:
I really like it. I know it could be trouble, if someone screwed up their window size completely and can't reset it anymore, but it's really convenient like this. Up to you, I guess, I would keep it this way.

Sounds good to me, thanks for the input!

**Comment by cspiegel** [comment]
I'm not entirely sure what's going on with the window position.  I think I'll get this code in as-is, and work on the window positioning at some point in the future.

**Comment by Schnubbirunkel** [comment]
Good idea. It's already so much better with this. The other problem is so common in windows software, I don't think anyone else would notice;) 
Thank you so much for your great work!
