### ISSUE TITLE
gargoyle-builddeb.sh conflict with qtads

### ISSUE THREAD

**Issue by salty-horse** [garglk/garglk#689]
The package built by the gargoyle-builddep script conflicts with Debian's qtads package ([list of files](https://packages.debian.org/bullseye/amd64/qtads/filelist))

Both packages provide this mimetype image:
`/usr/share/icons/hicolor/48x48/mimetypes/application-x-tads.png`

**Comment by cspiegel** [comment]
I'm not sure the best way to handle this. Ideally the TADS icon would be provided by standard icon themes, but of course it's not.  One possibility is to add QTads as a dependency.  Not pretty, but gets around the problem.  In general I'd consider this a distribution/vendor packaging issue, and leave it to them, but since Gargoyle _does_ include build scripts, no matter how unofficial, I suppose it should be addressed in them, at least.

Any ideas apart from a somewhat annoying dependency on a generally-unrelated package?

**Comment by salty-horse** [comment]
For personal use, maybe a flag could control if the generated package includes this image or not.

Maybe there's a recommended approach for handling this conflict. I don't know much about Debian packaging.

**Comment by cspiegel** [comment]
OK, I've got a pull request in #694 which does this.

**Comment by cspiegel** [comment]
Fixed in #694.
