### ISSUE TITLE
gli_startup not exported in 2023.1

### ISSUE THREAD

**Issue by curiousdannii** [garglk/garglk#756]
I've been doing some work on Frankendrift, and tried updating to the 2023.1 release, but now gli_startup is not exported. Or not exported properly. I see it using Dependency Walker, but it's not listed with dumpbin.

**Comment by cspiegel** [comment]
That's probably due to the C++ switch. `gli_startup` exists still, but will be name mangled.

Since this is an internal function, there's no guarantees made about its existence/structure.  However, I'm guessing that since Frankendrift is C#, it doesn't really fit in with Glk's model of taking over the main function, so needs to hack around it this way.

Given that, I think it's probably fine to provide access to Gargoyle's startup, to allow hooking into it from outside the "normal" Glk approach.  If that's the case, though, I'll want to rename it, since the `gli` prefix is for private, internal functionality.  Since the `garglk` prefix is used for Gargoyle extensions, calling it `garglk_startup` seems reasonable.  Once that's flagged as a public function, it'll be easier to remember to make sure it shouldn't change.

For 2023.1, you have a couple of options:

The mangled name can be use directly. At least on x86 and x86_64, the mangled name will be `_Z11gli_startupiPPc`.  This is a stopgap solution, of course...

Alternatively, you can rebuild Gargoyle and wrap the `gli_startup` declaration in `extern "C"` so it doesn't get mangled.  If you're going that route, you might want to rename it to `garglk_startup` at the same time, to match what will probably be the "official" name going forward.

If you'd like, since building Gargoyle for Windows is a bit finicky, I can make the name change locally, build it, and attach a DLL here.

**Comment by curiousdannii** [comment]
We can probably just keep testing with 2022.1 for now, and then when it's time to incorporate it into Gargoyle switch to garglk_startup.

**Comment by awlck** [comment]
It's relatively straightforward to try all three likely names (`gli_startup`, the mangled name for that, and `garglk_startup`) so that's what I've implemented.

**Comment by cspiegel** [comment]
Ok.  I'll get a change in to create `garglk_startup` for future releases (including any follow-on 2013.1 releases, if they're needed)

**Comment by cspiegel** [comment]
Pull request open at #758.  If there are problems, let me know, otherwise I'll get this merged in.
