### ISSUE TITLE
Gargoyle ignores theme declaration

### ISSUE THREAD

**Issue by alexispurslane** [garglk/garglk#767]
Version: `Gargoyle 2023.1`
OS: `Linux ... 6.2.2-arch1-1`
Package: `gargoyle` from the AUR, installed with `yay`

I've put `theme dark` in my `.config/garglk.ini`, but when Gargoyle launches it just ignores that and defaults to the normal light theme, which hurts my eyes. I've had a really long and bad day involving losing a save me and my gf have been playing on for weeks and having to completely reinstall my OS, so I'm probably missing something stupid, but I can't figure it out, so if you could help that'd be lovely. I really appreciate this program by the way, it's amazing <3

**Comment by cspiegel** [comment]
The very first question is whether the `theme` statement comes before, or after, all the `tcolor`, `gcolor`, etc.  `theme` is really just a fancy way of writing out the individual color declarations, which means they can override it if they come after.  If you're modifying the default config then it _should_ just work, since that's got it in the proper location.

I've got an Arch VM available so I can also try to install Gargoyle via the AUR there and see if I can reproduce this.

**Comment by alexispurslane** [comment]
The default config file that comes with gargoyle via the AUR actually doesn't even have a theme declaration in it at all. I put my theme Declaration at the very bottom of the file first and then tried putting it right below all the color declarations as well and it doesn't seem to work either way.

**Comment by Nephar** [comment]
Your Gargoyle might not be 2023.1, I believe linux version tells the version with _./gargoyle_app_name --version_, at least the AppImage from GitHub releases does. Can you check  that? And if the version happens to be old, you can always use the AppImage from releases here. That one works for Mint, should also work in Arch.

Also I believe _garlk.ini_ file ends with terp or game specific overrides, so it is not the best place for the theme declaration. The most logical place for theme would be as the last line of the _Colors and style definitions_ section.

**Comment by cspiegel** [comment]
> The default config file that comes with gargoyle via the AUR actually doesn't even have a theme declaration in it at all. I put my theme Declaration at the very bottom of the file first and then tried putting it right below all the color declarations as well and it doesn't seem to work either way.

@Nephar is correct about the location of the `theme` option in the config file.  And if you're using 2023.1 from AUR, it does include an updated `garglk.ini`.  I just built the AUR version, and `/etc/garglk.ini` has an entry for the theme. If you already had a configuration file from an earlier Gargoyle release, it won't get updated automatically; you've got to do it manually.  If that's the case, it'd explain why you're missing the theme entry.  I verified that dark mode does work fine in an AUR build of 2023.1.

One of these days I'll create a graphical config tool for Gargoyle which should make this all easier, but it's a fairly large task.

**Comment by alexispurslane** [comment]
> Your Gargoyle might not be 2023.1

I'll check that, but the package page says it's that version, and...

> You can also check for theme support by pressing Ctrl+Shift+t while running a story file. It should list all installed themes in a modal dialog. Keep in mind that the theme names are case-sensitive.

When I do this, it does list a number of themes, but when I type them in exactly as they are listed, it doesn't seem to do anything

**Comment by alexispurslane** [comment]
@cspiegel 

> If you already had a configuration file from an earlier Gargoyle release, it won't get updated automatically; you've got to do it manually

That would explain this behavior, combined with a bad location for the theme declaration. I'll try fixing all that!

**Comment by cspiegel** [comment]
I'm not sure how comfortable you are with the CLI, but as a note for anybody who stumbles across this, here's some tips on upgrading the config file:

Starting with 2023.1, I added some command-line options to Gargoyle.  You can pass `-d` to dump the default config file to stdout.  That can be redirected to a file, so:

```
$ gargoyle -d > config
```
Then you can pass the `-p` flag to see where Gargoyle looks for config files:

```
$ gargoyle -p
Configuration file paths:

/home/chris/.config/garglk.ini [user, non-existent]
/home/chris/.garglkrc [user]
/etc/garglk.ini [system, non-existent]
…
```
These are ordered from highest priority to lowest. In my case, there's no `~/.config/garglk.ini`, but there is `~/.garglkrc`, so that's what Gargoyle is using.  Now you can use your favorite diff tool to see the difference.  I use `vimdiff`, so something like this:

```
$ vimdiff config /home/chris/.garglkrc
```
Emacs looks like it has `M-x ediff` or `M-x ediff` modes to do similar things.

**Comment by alexispurslane** [comment]
Yeah as it turned out my theme declaration was just in the wrong place
