### ISSUE TITLE
Couldn't build terp/magnetic 2.3.1 under Ubuntu 20.04

### ISSUE THREAD

**Issue by cibersheep** [garglk/garglk#883]
https://github.com/garglk/garglk/blob/a682063f542cdf63388af166845d5e42189a9b44/terps/magnetic/Glk/glk.c#L6217C8-L6217C14

I had an error while building this terp even adding MACROS GARGLK to the CMakeList. Now I see there's because of the linkage section mentioned above.
I know this is very specific to me (under Linux compiling for Gelek and not for Garglk), but would it be fine if I split the current GARGLK cases into two? Something like TARGET_OS_UNIX, and GARGLK for the different cases?

**Comment by cspiegel** [comment]
Yes, that's no problem.  I've been working a bit to clean things up, but there are still sloppy areas like this where GARGLK is really a proxy to mean something else, e.g. a Unix Glk startup.

Just the other day I did this exact thing for Hugo.  It uses `HUGO_GLKUNIX`, so my recommendation is `MAGNETIC_GLKUNIX` for this code which provides the Unix Glk startup.

**Comment by cibersheep** [comment]
New MR :) #886 
Let me know if these changes work for Garglk

**Comment by curiousdannii** [comment]
Should each terp have its own glkunix macro, or could they all share one `GLKUNIX` one?

**Comment by cspiegel** [comment]
Different interpreters have different needs regarding the startup; some, like Glulxe, don't care at all where they're running; you have to link in the proper startup (e.g. `unixstrt.c`), but there's no need to set a macro. Others, like Bocfel, _do_ care.

And logically, the interpreters are all separate entities, so they shouldn't "share" a macro, so to speak; but if they both used the same macro name incidentally, it's no big deal either.  In the end, since this isn't a standard thing (Glk implementations identifying themselves), it's all ad hoc anyway.  I guess my thinking is, if Glk mandated that each implementation identify itself (`GLKUNIX`, `GLKWIN`, etc), then we'd just use that, but since it doesn't, defining a system-wide `GLKUNIX` macro won't do much good: maintained interpreters can't rely on it (because only Gargoyle would provide it), and "Gargoyle-maintained" interpreters can just do whatever they need.
