### ISSUE TITLE
Are there input colors?

### ISSUE THREAD

**Issue by shmup** [garglk/garglk#907]
Wondering if I can make sure my input stands out, bringing my eyes to the exact area when new text appears, really

So, that `>1` and `>1` for example:

![image](https://github.com/user-attachments/assets/3fbb9a67-c12d-4dcb-8931-43eaa2963794)

I'm not very savvy with gargoyle yet, scanned the stock garglk.ini to infer. Appears while the caret can have a color, the input can not?

**Comment by cspiegel** [comment]
It can!

The simplest way is with `tcolor` and `gcolor`. These set colors for text buffer and text grid windows. It's "documented" in the config file, but you'd want something like this:

```
tcolor 8 ff0000 000000
gcolor 8 ff0000 000000
```
That's red on black for both.  The syntax is:
```
[tg]color [style] [foreground] [background]
```
Style 8 is user input (the rest are commented in the config file). If your config file has a `theme` entry you'll need to set the input colors _after_ the theme, since theme declarations override all previous colors.

Which brings up the second, way to do colors: themes. Themes are documented at https://github.com/garglk/garglk/blob/master/THEMES.md, and provide a way to build an entire color theme in a somewhat more ergonomic way.

But if you just want to change the input, `tcolor` and `gcolor` are sufficient.

**Comment by shmup** [comment]
Thank you for the clarity, and mention of themes! Cheers @cspiegel

**Comment by cspiegel** [comment]
@shmup Was this accidentally reopened, or is there a problem with the input colors?
